[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['cd Backend && npm ci --only=production']

[phases.build]
cmds = ['cd Backend && npm run build']

[start]
cmd = 'cd Backend && npm start'