import { useEffect, useMemo, useState } from 'react'
import Button from '../components/ui/Button'
import Icon from '../components/ui/Icon'
import { apiRequest, getProducts } from '../services/api.service'

const useProducts = () => {
  const [state, setState] = useState({ items: [], loading: true, error: '' })
  const load = async () => { setState((old) => ({ ...old, loading: true, error: '' })); try { const result = await getProducts(); setState({ items: result.products || [], loading: false, error: '' }) } catch (error) { setState({ items: [], loading: false, error: error.message }) } }
  useEffect(() => { load() }, [])
  return { ...state, reload: load }
}

const formatNumber = (value) => new Intl.NumberFormat('en-IN').format(Number(value || 0))
const formatDate = (date) => date ? new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(date)) : '—'

function PageHeader({ title, subtitle, action }) { return <div className="utility-page__header"><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</div> }
function DataState({ loading, error, empty, children }) { if (loading) return <div className="utility-page__state">Loading data…</div>; if (error) return <div className="utility-page__state utility-page__state--error">{error}</div>; if (empty) return <div className="utility-page__state">No records found.</div>; return children }

export function Inventory() {
  const { items, loading, error, reload } = useProducts(); const [query, setQuery] = useState('')
  const visible = useMemo(() => items.filter((item) => `${item.name} ${item.sku} ${item.category}`.toLowerCase().includes(query.toLowerCase())), [items, query])
  return <div className="utility-page"><PageHeader title="Inventory" subtitle="Monitor stock levels and product availability." action={<Button icon="boxes" iconPosition="start" onClick={reload}>Refresh inventory</Button>} /><div className="utility-page__toolbar"><label><Icon name="search" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search inventory…" /></label></div><section className="utility-page__card"><DataState loading={loading} error={error} empty={!visible.length}><table className="utility-page__table"><thead><tr><th>Product</th><th>SKU</th><th>Warehouse</th><th>Available</th><th>Minimum</th><th>Status</th></tr></thead><tbody>{visible.map((item) => { const low = Number(item.current_stock) <= Number(item.minimum_stock); return <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.sku}</td><td>{item.warehouse || 'Main Warehouse'}</td><td>{formatNumber(item.current_stock)}</td><td>{formatNumber(item.minimum_stock)}</td><td><span className={`utility-page__pill ${low ? 'is-warning' : 'is-success'}`}>{low ? 'Low stock' : 'Available'}</span></td></tr> })}</tbody></table></DataState></section></div>
}

export function Operations() {
  const { items, loading, error, reload } = useProducts(); const [selected, setSelected] = useState(''); const [type, setType] = useState('in'); const [quantity, setQuantity] = useState(''); const [reason, setReason] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (event) => { event.preventDefault(); if (!selected) return setMessage('Select a product first.'); setBusy(true); setMessage(''); try { const result = await apiRequest(`/api/products/${selected}/stock/${type}`, { method: 'POST', body: JSON.stringify({ quantity: Number(quantity), reason }) }); setMessage(result.message); setQuantity(''); setReason(''); reload() } catch (requestError) { setMessage(requestError.message) } finally { setBusy(false) } }
  return <div className="utility-page"><PageHeader title="Operations" subtitle="Record inbound and outbound stock movements." /><div className="utility-page__split"><section className="utility-page__card utility-page__form-card"><h3>New stock movement</h3><form onSubmit={submit}><label>Product<select value={selected} onChange={(event) => setSelected(event.target.value)} required><option value="">Select product</option>{items.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.sku}</option>)}</select></label><label>Movement type<select value={type} onChange={(event) => setType(event.target.value)}><option value="in">Stock in</option><option value="out">Stock out</option></select></label><label>Quantity<input type="number" min="1" value={quantity} onChange={(event) => setQuantity(event.target.value)} required /></label><label>Reason<input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="e.g. Purchase order received" /></label>{message && <p className="utility-page__message">{message}</p>}<Button type="submit" icon="plus" iconPosition="start" disabled={busy}>{busy ? 'Saving…' : 'Record movement'}</Button></form></section><section className="utility-page__card"><h3>Current stock</h3><DataState loading={loading} error={error} empty={!items.length}><div className="utility-page__stock-list">{items.slice(0, 7).map((item) => <div key={item.id}><span><strong>{item.name}</strong><small>{item.sku}</small></span><b>{formatNumber(item.current_stock)}</b></div>)}</div></DataState></section></div></div>
}

export function Reports() {
  const { items, loading, error } = useProducts(); const totalStock = items.reduce((sum, item) => sum + Number(item.current_stock || 0), 0); const lowStock = items.filter((item) => Number(item.current_stock) <= Number(item.minimum_stock)).length; const value = items.reduce((sum, item) => sum + Number(item.current_stock || 0) * Number(item.unit_price || 0), 0)
  return <div className="utility-page"><PageHeader title="Reports" subtitle="A live operational snapshot based on your current inventory." action={<Button icon="download" iconPosition="start" onClick={() => window.print()}>Print report</Button>} /><DataState loading={loading} error={error} empty={false}><div className="utility-page__metrics"><div><span>Total inventory units</span><strong>{formatNumber(totalStock)}</strong></div><div><span>Inventory value</span><strong>₹{formatNumber(value)}</strong></div><div><span>Low-stock products</span><strong>{formatNumber(lowStock)}</strong></div></div><section className="utility-page__card"><h3>Inventory by category</h3><div className="utility-page__category-list">{Object.entries(items.reduce((result, item) => ({ ...result, [item.category || 'Uncategorised']: (result[item.category || 'Uncategorised'] || 0) + Number(item.current_stock || 0) }), {})).map(([category, stock]) => <div key={category}><span>{category}</span><b>{formatNumber(stock)} units</b></div>)}</div></section></DataState></div>
}

export function Settings() { const [saved, setSaved] = useState(() => localStorage.getItem('opsflow-settings') === 'true'); const [email, setEmail] = useState(() => localStorage.getItem('opsflow-email-notifications') !== 'false'); const save = () => { localStorage.setItem('opsflow-settings', 'true'); localStorage.setItem('opsflow-email-notifications', String(email)); setSaved(true) }; return <div className="utility-page"><PageHeader title="Settings" subtitle="Manage your workspace preferences." /><section className="utility-page__card utility-page__form-card"><h3>Notifications</h3><label className="utility-page__check"><input type="checkbox" checked={email} onChange={(event) => setEmail(event.target.checked)} />Email me about low-stock alerts and challan updates</label><Button onClick={save}>Save preferences</Button>{saved && <p className="utility-page__message">Preferences saved on this device.</p>}</section></div> }

export function System({ user }) { return <div className="utility-page"><PageHeader title="System" subtitle="Workspace account and system information." /><div className="utility-page__split"><section className="utility-page__card"><h3>Signed-in user</h3><div className="utility-page__profile"><span>{user.firstName?.[0] || 'A'}</span><div><strong>{user.name}</strong><p>{user.email}</p><small>{user.roleLabel}</small></div></div></section><section className="utility-page__card"><h3>Application status</h3><div className="utility-page__stock-list"><div><span><strong>Frontend</strong><small>React workspace</small></span><b className="utility-page__pill is-success">Online</b></div><div><span><strong>Data API</strong><small>API-backed operational modules</small></span><b className="utility-page__pill is-success">Configured</b></div></div></section></div></div> }
